name: Bug Report
description: Report a bug or unexpected behavior in Kifa.
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Run `kifa daemon --stdin`
        2. Send input via pipe
        3. Observe error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Kifa version
      description: Output of `kifa --version` or the commit hash.
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or error output
      description: Any relevant log output, panic backtraces, or error messages.
      render: text
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other relevant information (configuration, data sources, environment details).
    validations:
      required: false
